name: flutter_midi
description: A Flutter Plugin to Play midi on iOS and Android.
version: 1.1.1
author: Rody Davis <rody.davis.jr@gmail.com>
homepage: https://github.com/rodydavis/flutter_midi

environment:
  sdk: ">=3.2.0"
  flutter: ">= 3.16.5"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3
  path_provider: ^2.0.5
  plugin_platform_interface: ^2.0.1
  tonic: ^0.2.4

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterMidiPlugin
dev_dependencies:
  flutter_test:
    sdk: flutter
